name: "Create and release web app"
permissions:
   actions: write
   packages: write
   contents: write

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            ref: ${{ github.ref }}
            fetch-depth: 0

        - name: Install GitVersion
          uses: gittools/actions/gitversion/setup@v3.0
          with:
            versionSpec: '5.x'

        - name: Determine Version
          id: gitversion
          uses: gittools/actions/gitversion/execute@v3.0

        - name: Set up .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x

        - name: Build with dotnet HMSBlazor
          run: dotnet build code/final/forms_migrated/HmsBlazor/HmsBlazor/HmsBlazor.csproj --configuration Release
    
        - name: Publish with dotnet (Frontend)
          run: dotnet publish code/final/forms_migrated/HmsBlazor/HmsBlazor/HmsBlazor.csproj -c Release

        - name: Zip artifact for deployment
          run: |
            zip hms_blazor.zip code/final/forms_migrated/HmsBlazor/HmsBlazor/bin/Release/net8.0/publish/* -r

        - name: Create a release with version provided by package push
          uses: softprops/action-gh-release@v2
          with:
            token: "${{ secrets.GITHUB_TOKEN }}"
            tag_name: "v${{ env.GitVersion_SemVer }}"
            generate_release_notes: true
            files: |
              hms_blazor.zip
